### ISSUE TITLE
Add text style when a know time is found

### ISSUE THREAD

**Issue by Karan-Gandhi** [Karan-Gandhi/Todo-application#4]
## Demo
Implement something like this:

![Video](https://cdn.dribbble.com/users/149817/screenshots/3461827/text-animation3.gif)

Currently using `SpannableString` to get the underline effect. If we use an Interval which calls a function after a specific timelimit then the current cursor position is lost and if we use `EditText.addTextChangeListener(...)` then it gets stuck in the recursion loop.
__________________________________
### Todo
- [ ] Search the string for finding known time or dates
- [ ] Add the underline effect
  - [ ] Add the effect
  - [ ] Add the animation
- [ ] Add the `Snackbar` for asking weather you want to add the time
- [ ] dynamically update the time based on the clock widget.
- [ ] Add the task based on the time found.

### Links
 - https://stackoverflow.com/questions/63206510/underline-text-while-typing-in-edittext-android
 - https://stackoverflow.com/questions/63213800/can-stylespan-updatedrawstate-be-used-to-animate-spannablestring-android
 - https://stackoverflow.com/questions/4283755/implementing-a-rich-text-editor-in-android
 - https://stackoverflow.com/questions/56614714/is-there-a-way-a-way-to-animate-setting-backgroundcolorspan-to-spannablestring
